// eslint-disable-next-line import/no-anonymous-default-export
export default {
  "login": "zuzanakorma",
  "id": 70716716,
  "node_id": "MDQ6VXNlcjcwNzE2NzE2",
  "avatar_url": "https://avatars.githubusercontent.com/u/70716716?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/zuzanakorma",
  "html_url": "https://github.com/zuzanakorma",
  "followers_url": "https://api.github.com/users/zuzanakorma/followers",
  "following_url": "https://api.github.com/users/zuzanakorma/following{/other_user}",
  "gists_url": "https://api.github.com/users/zuzanakorma/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/zuzanakorma/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/zuzanakorma/subscriptions",
  "organizations_url": "https://api.github.com/users/zuzanakorma/orgs",
  "repos_url": "https://api.github.com/users/zuzanakorma/repos",
  "events_url": "https://api.github.com/users/zuzanakorma/events{/privacy}",
  "received_events_url": "https://api.github.com/users/zuzanakorma/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Zuzana",
  "company": null,
  "blog": "",
  "location": "Amsterdam",
  "email": null,
  "hireable": null,
  "bio": "Full-Stack Developer",
  "twitter_username": null,
  "public_repos": 29,
  "public_gists": 0,
  "followers": 2,
  "following": 5,
  "created_at": "2020-09-03T17:17:12Z",
  "updated_at": "2023-12-18T13:54:01Z"
};
